[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
protobuf = { id = "com.google.protobuf", version = "0.9.5" }
spring-boot = { id = "org.springframework.boot", version = "4.0.0" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "2.2.21" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version = "2.2.21" }
jesperancinha-omni = { id = "org.jesperancinha.plugins.omni", version = "0.4.5" }

[libraries]
grpc-kotlin-stub = { group = "io.grpc", name = "grpc-kotlin-stub", version = "1.5.0" }
grpc-protobuf = { group = "io.grpc", name = "grpc-protobuf", version = "1.77.0" }
grpc-stub = { group = "io.grpc", name = "grpc-stub", version = "1.77.0" }
grpc-netty = { group = "io.grpc", name = "grpc-netty", version = "1.77.0" }
protoc-gen-grpc-java = { group = "io.grpc", name = "protoc-gen-grpc-java", version = "1.77.0" }
protoc-gen-grpc-kotlin = { group = "io.grpc", name = "protoc-gen-grpc-kotlin", version = "1.5.0" }
protoc = { group = "com.google.protobuf", name = "protoc", version = "4.33.1" }
protobuf-java-util = { group = "com.google.protobuf", name = "protobuf-java-util", version = "4.33.1" }
protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version = "4.33.1" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "6.0.1" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "6.0.1" }
spring-boot-starter-data-r2dbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-r2dbc", version = "4.0.0" }
springdoc-openapi-starter-webflux-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-ui", version = "3.0.0" }
r2dbc-postgresql = { group = "org.postgresql", name = "r2dbc-postgresql", version = "1.1.1.RELEASE" }
